name: Publish Docker Branch
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get branch
      run: echo ::set-env name=BRANCH::${GITHUB_REF#refs/heads/}
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        VERSION: ${{ github.sha }}
      with:
        name: wreave/tautulli
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        buildargs: VERSION, BRANCH
